--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: greetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.greetings (
    first_word character varying(64),
    body character varying(512),
    id integer NOT NULL
);


ALTER TABLE public.greetings OWNER TO postgres;

--
-- Name: greetings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.greetings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.greetings_id_seq OWNER TO postgres;

--
-- Name: greetings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.greetings_id_seq OWNED BY public.greetings.id;


--
-- Name: irc_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.irc_users (
    id integer NOT NULL,
    created_on timestamp without time zone,
    username character varying(64)
);


ALTER TABLE public.irc_users OWNER TO postgres;

--
-- Name: irc_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.irc_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.irc_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: relay_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.relay_messages (
    id integer NOT NULL,
    "timestamp" timestamp without time zone,
    from_user character varying(64),
    to_user character varying(64),
    description text,
    suggested_url character varying(4096),
    was_relayed boolean DEFAULT false,
    from_channel character varying(512)
);


ALTER TABLE public.relay_messages OWNER TO postgres;

--
-- Name: relay_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.relay_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relay_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: greetings id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.greetings ALTER COLUMN id SET DEFAULT nextval('public.greetings_id_seq'::regclass);


--
-- Name: greetings greetings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.greetings
    ADD CONSTRAINT greetings_pkey PRIMARY KEY (id);


--
-- Name: irc_users irc_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.irc_users
    ADD CONSTRAINT irc_users_pkey PRIMARY KEY (id);


--
-- Name: relay_messages relay_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relay_messages
    ADD CONSTRAINT relay_messages_pkey PRIMARY KEY (id);


--
-- Name: TABLE greetings; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.greetings TO benevolentuser;


--
-- Name: TABLE irc_users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.irc_users TO benevolentuser;


--
-- Name: SEQUENCE irc_users_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.irc_users_id_seq TO benevolentuser;


--
-- Name: TABLE relay_messages; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.relay_messages TO benevolentuser;


--
-- Name: SEQUENCE relay_messages_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.relay_messages_id_seq TO benevolentuser;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: benevolentuser
--

ALTER DEFAULT PRIVILEGES FOR ROLE benevolentuser IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES  TO benevolentuser;


--
-- PostgreSQL database dump complete
--

