--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: irc_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.irc_users (
    id integer NOT NULL,
    created_on timestamp without time zone,
    username character varying(64)
);


ALTER TABLE public.irc_users OWNER TO postgres;

--
-- Name: irc_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.irc_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.irc_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: relay_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.relay_messages (
    id integer NOT NULL,
    "timestamp" timestamp without time zone,
    from_user character varying(64),
    to_user character varying(64),
    description text,
    url character varying(4096)
);


ALTER TABLE public.relay_messages OWNER TO postgres;

--
-- Name: relay_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.relay_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relay_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: relay_url; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.relay_url (
    id integer NOT NULL,
    "timestamp" timestamp without time zone,
    from_user character varying(64),
    to_user character varying(64),
    description text,
    url character varying(4096),
    relayed_on timestamp without time zone,
    was_relayed boolean DEFAULT false
);


ALTER TABLE public.relay_url OWNER TO postgres;

--
-- Name: relay_url_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.relay_url ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relay_url_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: irc_users irc_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.irc_users
    ADD CONSTRAINT irc_users_pkey PRIMARY KEY (id);


--
-- Name: relay_messages relay_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relay_messages
    ADD CONSTRAINT relay_messages_pkey PRIMARY KEY (id);


--
-- Name: relay_url relay_url_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relay_url
    ADD CONSTRAINT relay_url_pkey PRIMARY KEY (id);


--
-- Name: TABLE irc_users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.irc_users TO benuser;


--
-- Name: SEQUENCE irc_users_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.irc_users_id_seq TO benuser;


--
-- Name: TABLE relay_messages; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.relay_messages TO benuser;


--
-- Name: SEQUENCE relay_messages_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.relay_messages_id_seq TO benuser;


--
-- Name: TABLE relay_url; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.relay_url TO benuser;


--
-- Name: SEQUENCE relay_url_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.relay_url_id_seq TO benuser;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: benuser
--

ALTER DEFAULT PRIVILEGES FOR ROLE benuser IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES  TO benuser;


--
-- PostgreSQL database dump complete
--

